# Generated by Django 6.0.4 on 2026-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('services', 'Services'), ('experience', 'Experience'), ('work', 'Case Studies'), ('results', 'Results'), ('testimonials', 'Testimonials')], max_length=40, unique=True)),
                ('eyebrow', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Section Content',
            },
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
